version: "3"
services:
  storefront:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: ["npm", "run", "dev"]
    volumes:
      - /usr/server/app
    environment:
      - VENDURE_API_URL=http://localhost:3001/shop-api
